// LOCALHOST
###
GET http://localhost:3000/contacts
###
GET http://localhost:3000/contacts/65f8f4a0b17926596eac8145
###
GET http://localhost:3000/contacts/65f8f4aab17926596eac9dd5
###
GET http://localhost:3000/contacts/65f8f4b3b17926596eacb805

// PRODUCTION Deploy
###
GET https://cse341-personal-assignment-lciu.onrender.com/contacts
###
GET https://cse341-personal-assignment-lciu.onrender.com/contacts/65f8f4a0b17926596eac8145
###
GET https://cse341-personal-assignment-lciu.onrender.com/contacts/65f8f4aab17926596eac9dd5
###
GET https://cse341-personal-assignment-lciu.onrender.com/contacts/65f8f4b3b17926596eacb805